### ISSUE TITLE
dmaker.fan.p18 support (Mi Smart Standing Fan 2)

### ISSUE THREAD

**Issue by fk-online** [stason325/node-red-contrib-miio-localdevices#2]
Hello!

First of all i would like to thank you for this great node expansion!

I would request to support the device **dmaker.fan.p18**
I hope that this device is compatible.

Many thanks in advance and best regards, fk-online

**Comment by stason325** [comment]
Hello and thank you for your interest!

I added 6 fans in the latest 0.5.5 including **dmaker.fan.p18** that you requested. Please see _3) Heaters, Fans & Toilet_ section in DEVICES.md for details.

**Comment by fk-online** [comment]
Hello and thank you for the really quick response!


I have integrated the device as described (previously worked perfectly with viomi.vacuum.v7 and continues to work after the update / re-installation).

Unfortunately, I get an error message when Auto-Polling and also when sending commands (the same error):
![Config](https://user-images.githubusercontent.com/98700730/169354948-7a84ae1c-f2b5-4b30-814f-80adac3f06f4.PNG)

My testing flow looks like this:
![Flow](https://user-images.githubusercontent.com/98700730/169354986-fd515387-86c1-490b-94cb-8618dc6781c9.PNG)

I have also tested the configuration with Cloud Auth, unfortunately without success.

The app connection to the device works perfectly.

Thank you for your time, best regards!

**Comment by stason325** [comment]
Well, it has not become as easy as I expected initially :)
Comparing with viomi.vacuum.v7 (which is miio-device) it could be more complicated because dmaker.fan.p18 is miot cloud device.

What I see here is that you do not have right connection with the device on initialisation (msg.payload from get-node is empty). So it is no sense to try any commands, or to switch on auto-polling option.

First step is to establish that connection on init. The indicator that will show that this connection was successfully established is getting JSON with device properties and values in msg.payload from get-node.
To reach that we need to work a bit with defFile.

What I propose is to go Telegram  to make our communication more prompt. You can find me there as @stason_bims
In Telegram I can share updated defFiles with you faster.

**Comment by drdigital-ips** [comment]
Is there already a solution?
I would also like to use my dmaker.fan.p18.

**Comment by stason325** [comment]
> Is there already a solution?
> I would also like to use my dmaker.fan.p18.

Hello, we found out with [fk-online](https://github.com/fk-online) that he gets some issues with connection and feedback from his device due to firewall.

Please try defFile in current version 0.5.5 and come back here with pictures of debug of msg.payload from GET-node. It seems to me that it could work properly. If not I have some ideas how to fix things and I will update it in next 0.5.6 version of nodes.

**Comment by drdigital-ips** [comment]
I first tried it with NodeRed in a Docker container.
Then to be on the safe side directly in a separate VM.
But I get the same error with both.
![image](https://user-images.githubusercontent.com/62700903/170488964-75e86d0e-3a28-468f-8442-ff05d3c895dd.png)

**Comment by stason325** [comment]
> I first tried it with NodeRed in a Docker container.
> Then to be on the safe side directly in a separate VM.
> But I get the same error with both.
> I've also tried it with and without cloud login.
> ![image](https://user-images.githubusercontent.com/62700903/170488964-75e86d0e-3a28-468f-8442-ff05d3c895dd.png)

Did you get any initial data in debug from GET-node after deploying? I see it only from SEND-node

**Comment by drdigital-ips** [comment]
First Deploy withot send.
![image](https://user-images.githubusercontent.com/62700903/170490977-041076bd-c8e6-42c6-9785-94c1e1135653.png)

**Comment by stason325** [comment]
[fk-online](https://github.com/fk-online) and [drdigital-ips](https://github.com/drdigital-ips),

I updated the nodes. Latest version 0.5.6 includes an updated defFile for **dmaker.fan.p18** that was fully tested with [drdigital-ips](https://github.com/drdigital-ips) and seems to work perfect.

Could we close the issue?

Regards.

**Comment by drdigital-ips** [comment]
For me it works perfect.
Many Thanks for that great work!!!

**Comment by fk-online** [comment]
I can control the devices but i don't get any feedback from them - but that's because of my network and not caused by your NR extension. 
Thank you very much for the great support!
Best regards

**Comment by mema0007** [comment]
I get the error "Model dmaker.fan.p18 is not supported". The node MIIOgetdata sends no messages and after sending a message to the node MIIOsencommand the state under the node is permanent "Connecting...".
