### ISSUE TITLE
dmaker.airfresh.a1 

### ISSUE THREAD

**Issue by Osrx** [stason325/node-red-contrib-miio-localdevices#6]
Sorry, but what I'm doing wrong?

`15 Jun 21:53:14 - [error] [MIIOdevices:04a4457b7f046bf1] Error: Model dmaker.airfresh.a1 is not supported at Object.createDevice [as device] (/opt/iobroker/iobroker-data/node-red/node_modules/node-mihome/lib/device.js:8:11) at new MIIOdevicesNode (/opt/iobroker/iobroker-data/node-red/node_modules/node-red-contrib-miio-localdevices/nodes/devices.js:62:27) at Object.createNode (/opt/iobroker/node_modules/@node-red/runtime/lib/flows/util.js:90:27) at Flow.start (/opt/iobroker/node_modules/@node-red/runtime/lib/flows/Flow.js:180:44) at start (/opt/iobroker/node_modules/@node-red/runtime/lib/flows/index.js:371:33)
--`
Node-red v2.2.2 inside docker container on Raspberry Pi 4b

Thank you!

**Comment by stason325** [comment]
> Sorry, but what I'm doing wrong?
> 
> `15 Jun 21:53:14 - [error] [MIIOdevices:04a4457b7f046bf1] Error: Model dmaker.airfresh.a1 is not supported at Object.createDevice [as device] (/opt/iobroker/iobroker-data/node-red/node_modules/node-mihome/lib/device.js:8:11) at new MIIOdevicesNode (/opt/iobroker/iobroker-data/node-red/node_modules/node-red-contrib-miio-localdevices/nodes/devices.js:62:27) at Object.createNode (/opt/iobroker/node_modules/@node-red/runtime/lib/flows/util.js:90:27) at Flow.start (/opt/iobroker/node_modules/@node-red/runtime/lib/flows/Flow.js:180:44) at start (/opt/iobroker/node_modules/@node-red/runtime/lib/flows/index.js:371:33) --` Node-red v2.2.2 inside docker container on Raspberry Pi 4b
> 
> Thank you!

Hi there.
I haven't tested my nodes in a bundle of NR+Iobroker+ Docker, but according to the logs "node-mihome" library can't find  dmaker.airfresh.a1 in its list of supported devices.

It could happen because you didn't paste defFile for your device to target folder. In case of dmaker.airfresh.a1 you must copy-paste defFile (please see DEVICES.md table for your device).

Please see instruction for copy-pasting  here: https://github.com/stason325/node-red-contrib-miio-localdevices#send-node (item 3).

Regards

**Comment by Osrx** [comment]
You are absolutely right!
All become working as it should after coping file in a right place!
Thank you a lot for your work.

**Comment by stason325** [comment]
> You are absolutely right!
> 
> All become working as it should after coping file in a right place!
> 
> Thank you a lot for your work.
> 
> 

Enjoy! 😄
